# Generated by Django 5.1.1 on 2024-09-13 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2024, 9, 13, 17, 9, 36, 703335, tzinfo=datetime.timezone.utc))),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('PL', 'PLAIN'), ('GI', 'GINGER'), ('EL', 'ELIACHI')], max_length=2)),
            ],
        ),
    ]
