# Generated by Django 5.1.1 on 2024-09-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=400)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('product', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='blog.product')),
            ],
        ),
    ]
