# Generated by Django 5.1.1 on 2024-09-14 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai',
            name='discription',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='chai',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 5, 38, 3, 135314, tzinfo=datetime.timezone.utc)),
        ),
    ]
