# Generated by Django 5.1.1 on 2024-09-14 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_chai_discription_alter_chai_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chai',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 5, 41, 0, 184347, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chai',
            name='discription',
            field=models.TextField(default='this feild is empty'),
        ),
    ]
