# Generated by Django 5.1.1 on 2024-09-14 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_chai_date_added_alter_chai_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai',
            name='price',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='chai',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 5, 42, 42, 657381, tzinfo=datetime.timezone.utc)),
        ),
    ]
