# Generated by Django 5.1.1 on 2024-09-14 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_chai_date_added_alter_chai_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai',
            name='total_price',
            field=models.IntegerField(default='9'),
        ),
        migrations.AlterField(
            model_name='chai',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 5, 46, 54, 653281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chai',
            name='price',
            field=models.IntegerField(default='9'),
        ),
    ]
