# Generated by Django 5.1.1 on 2024-09-14 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_chai_total_price_alter_chai_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chai',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 5, 47, 1, 430327, tzinfo=datetime.timezone.utc)),
        ),
    ]
